# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/.next'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/.next.zip'
    replaceExistingArchive: true
  displayName: 'Archive build artifact'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Publish build artifact'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'nginx-dev-con'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    contents: '**'
    targetFolder: '/tmp'
  displayName: 'Copy build artifact to Ubuntu machine'

- task: SSH@0
  inputs:
    sshEndpoint: 'nginx-dev-con'
    runOptions: 'commands'
    commands: |
      unzip /tmp/.next.zip -d /tmp/.next
      # mv -f .next/BUILD_ID /var/www/html/BUILD_ID
    failOnStdErr: false
    readyTimeout: '20000'
  displayName: 'Unpack build artifact on ubuntu machine'
- task: SSH@0
  inputs:
    sshEndpoint: 'nginx-dev-con'
    runOptions: 'commands'
    commands: |
      sudo rm -rf /var/www/html/*
      sudo mv /tmp/.next/* /var/www/html
    interactiveSession: true
    readyTimeout: '20000'
    interactiveKeyboardAuthentication: true
  displayName: 'Move build output to /var/www/html on Ubuntu machine'
